version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  server:
    build: .
    ports:
      - 5000:80
    depends_on:
      - mongo
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./:/app
volumes:
  mongo-data:
